/**
 * Resolves imagery for any place page from the build-time Pexels manifest.
 *
 * The manifest (src/data/place-images.json) is generated by
 * `npm run images:pexels`. Nothing here calls the Pexels API — the key is
 * build-only, and pages render from static data.
 *
 * Coverage is deliberately partial: we curate photos for the places we publish
 * hub pages for, and everything else (any of the ~8,900 generated IATA
 * airports) walks a fallback chain up to its city, then its country, then a
 * neutral default. Every lookup therefore returns an image.
 */
import manifest from "@/data/place-images.json";
import { MARKETS } from "@/data/markets";

export type PlaceImage = {
  id: number;
  photographer: string;
  photographerUrl: string;
  pexelsUrl: string;
  alt: string;
  avgColor: string;
  width: number;
  height: number;
  src: string;
  query: string;
};

const IMAGES = manifest.images as Record<string, PlaceImage>;

/** Country display name → market slug, so curated airports can reach a country image. */
const COUNTRY_SLUG_BY_NAME = new Map(MARKETS.map((m) => [m.name.toLowerCase(), m.slug]));

function lookup(...keys: (string | undefined | null)[]): PlaceImage | undefined {
  for (const key of keys) {
    if (!key) continue;
    const hit = IMAGES[key];
    if (hit) return hit;
  }
  return undefined;
}

/** Neutral defaults — always present in the manifest, so resolution never fails. */
function fallback(kind: "airport" | "city" | "road" | "hero"): PlaceImage {
  return IMAGES[`fallback:${kind}`] ?? IMAGES["fallback:hero"];
}

// ------------------------------------------------------------------ resolvers

/**
 * Country imagery. Accepts either a market slug ("greece") or an ISO country
 * code ("GR") — the manifest carries both, because market hub pages are keyed
 * by slug while the worldwide IATA catalog only knows codes.
 */
export function getCountryImage(country?: string): PlaceImage {
  if (!country) return fallback("city");
  return lookup(`country:${country}`, `country:${country.toUpperCase()}`) ?? fallback("city");
}

export function getCityImage(citySlug?: string, countrySlug?: string): PlaceImage {
  return (
    lookup(citySlug && `city:${citySlug}`, countrySlug && `country:${countrySlug}`) ??
    fallback("city")
  );
}

export function getRegionImage(regionSlug?: string): PlaceImage {
  return lookup(regionSlug && `region:${regionSlug}`, "country:greece") ?? fallback("city");
}

export function getServiceImage(serviceSlug?: string): PlaceImage {
  return lookup(serviceSlug && `service:${serviceSlug}`) ?? fallback("road");
}

/**
 * Airport imagery, widest to narrowest: the airport's own photo, then its city,
 * then its country, then a generic terminal. Generated IATA airports have no
 * entry of their own and land on the city or country step.
 */
export function getAirportImage(airport: {
  iata?: string;
  citySlug?: string;
  /** Market slug, e.g. "greece". */
  countrySlug?: string;
  /** ISO code, e.g. "GR" — what the worldwide IATA catalog carries. */
  countryCode?: string;
  /** Display name, e.g. "Greece" — curated airports store this. */
  country?: string;
}): PlaceImage {
  const countrySlug =
    airport.countrySlug ?? COUNTRY_SLUG_BY_NAME.get((airport.country ?? "").toLowerCase());

  return (
    lookup(
      airport.iata && `airport:${airport.iata.toUpperCase()}`,
      airport.citySlug && `city:${airport.citySlug}`,
      countrySlug && `country:${countrySlug}`,
      airport.countryCode && `country:${airport.countryCode.toUpperCase()}`,
    ) ?? fallback("airport")
  );
}

/** The homepage / generic marketing hero. */
export function getHeroImage(): PlaceImage {
  return fallback("hero");
}

// ---------------------------------------------------------------- url builder

export type ImageSizeOptions = {
  width: number;
  /** Omit to keep the photo's own aspect ratio instead of cropping. */
  height?: number;
  /** 1–2. Use 2 for small fixed-size cards on retina displays. */
  dpr?: 1 | 2;
};

/**
 * Builds a sized delivery URL. Pexels resizes and re-compresses on its CDN, so
 * we never store derivatives — ask for exactly the pixels the layout needs.
 */
export function imageUrl(image: PlaceImage, { width, height, dpr }: ImageSizeOptions): string {
  const params = new URLSearchParams({
    auto: "compress",
    cs: "tinysrgb",
    w: String(width),
  });
  if (height) {
    params.set("h", String(height));
    params.set("fit", "crop");
  }
  if (dpr) params.set("dpr", String(dpr));
  return `${image.src}?${params.toString()}`;
}

/** Tiny blurred placeholder to paint while the real file loads. */
export function imagePlaceholder(image: PlaceImage): string {
  return `${image.src}?auto=compress&cs=tinysrgb&w=24`;
}

/**
 * Absolute 1200×630 URL for og:image / twitter:image. Social scrapers reject
 * relative paths, and the Pexels CDN is already absolute.
 */
export function imageOgUrl(image: PlaceImage): string {
  return imageUrl(image, { width: 1200, height: 630 });
}

/**
 * Attribution line. The Pexels API guidelines require crediting the
 * photographer wherever their photo appears — <PhotoCredit> renders this.
 */
export function imageCredit(image: PlaceImage) {
  return {
    photographer: image.photographer,
    photographerUrl: image.photographerUrl,
    photoUrl: image.pexelsUrl,
  };
}
