/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesSlugRouteImport } from './routes/routes.$slug'
import { Route as BookSuccessRouteImport } from './routes/book.success'

const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/routes/$slug',
  path: '/routes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSuccessRoute = BookSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/fleet': typeof FleetRoute
  '/book/success': typeof BookSuccessRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/fleet': typeof FleetRoute
  '/book/success': typeof BookSuccessRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/fleet': typeof FleetRoute
  '/book/success': typeof BookSuccessRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/fleet'
    | '/book/success'
    | '/routes/$slug'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/fleet' | '/book/success' | '/routes/$slug' | '/routes'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/fleet'
    | '/book/success'
    | '/routes/$slug'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  FleetRoute: typeof FleetRoute
  RoutesSlugRoute: typeof RoutesSlugRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/success': {
      id: '/book/success'
      path: '/success'
      fullPath: '/book/success'
      preLoaderRoute: typeof BookSuccessRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookSuccessRoute: typeof BookSuccessRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSuccessRoute: BookSuccessRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  FleetRoute: FleetRoute,
  RoutesSlugRoute: RoutesSlugRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
