/**
 * Full IATA airport catalog (OurAirports), generated by scripts/generate-iata-airports.mjs
 * Row: [iata, name, city, countryCode, lat, lng]
 */
import raw from "./iata-airports.json";

export type IataAirportRow = [
  iata: string,
  name: string,
  city: string,
  countryCode: string,
  lat: number,
  lng: number,
];

type RawFile = {
  countries: Record<string, string>;
  airports: IataAirportRow[];
};

const data = raw as unknown as RawFile;

export const IATA_COUNTRY_NAMES: Record<string, string> = data.countries;
export const IATA_AIRPORTS: IataAirportRow[] = data.airports;

export type IataAirport = {
  iata: string;
  name: string;
  city: string;
  countryCode: string;
  countryName: string;
  lat: number;
  lng: number;
  label: string;
};

function toAirport(row: IataAirportRow): IataAirport {
  const [iata, name, city, countryCode, lat, lng] = row;
  const countryName = IATA_COUNTRY_NAMES[countryCode] ?? countryCode;
  const label = city ? `${name} (${iata})` : `${name} (${iata})`;
  return { iata, name, city, countryCode, countryName, lat, lng, label };
}

const byIata = new Map<string, IataAirport>();
for (const row of IATA_AIRPORTS) {
  byIata.set(row[0], toAirport(row));
}

export function getIataAirport(iata: string): IataAirport | undefined {
  return byIata.get(iata.toUpperCase());
}

export function getCountryName(code: string): string {
  return IATA_COUNTRY_NAMES[code.toUpperCase()] ?? code;
}

/** Fast prefix / includes search over all IATA airports. */
export function searchIataAirports(query: string, limit = 12): IataAirport[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const exactIata: IataAirport[] = [];
  const prefixIata: IataAirport[] = [];
  const nameHits: IataAirport[] = [];

  for (const row of IATA_AIRPORTS) {
    const a = byIata.get(row[0])!;
    const iata = a.iata.toLowerCase();
    const name = a.name.toLowerCase();
    const city = a.city.toLowerCase();
    const country = a.countryName.toLowerCase();

    if (iata === q) {
      exactIata.push(a);
      continue;
    }
    if (iata.startsWith(q)) {
      prefixIata.push(a);
      continue;
    }
    if (
      name.startsWith(q) ||
      city.startsWith(q) ||
      name.includes(q) ||
      city.includes(q) ||
      country.startsWith(q)
    ) {
      nameHits.push(a);
    }
    if (exactIata.length + prefixIata.length + nameHits.length > limit * 4) break;
  }

  return [...exactIata, ...prefixIata, ...nameHits].slice(0, limit);
}

/** Popular / large hubs for empty-state when no country context — worldwide first. */
export const FEATURED_IATA = [
  "LHR", "CDG", "AMS", "FRA", "FCO", "MXP", "BCN", "MAD", "LIS", "DUB",
  "ATH", "IST", "DXB", "DOH", "AUH",
  "JFK", "EWR", "LAX", "ORD", "MIA", "SFO", "YYZ",
  "SIN", "HKG", "NRT", "ICN", "BKK", "SYD", "MEL",
  "HER", "CHQ", "SKG", "JTR", "JMK", "RHO", "CFU", "ZTH",
  "BER", "MUC", "VIE", "ZRH", "CPH", "ARN", "OSL", "HEL",
  "GRU", "EZE", "JNB", "CAI", "TLV", "BOM", "DEL",
] as const;

export function featuredAirports(limit = 12): IataAirport[] {
  return FEATURED_IATA.map((c) => byIata.get(c)).filter(Boolean).slice(0, limit) as IataAirport[];
}

export function airportsInCountry(countryCode: string, limit = 12): IataAirport[] {
  const cc = countryCode.toUpperCase();
  const hits: IataAirport[] = [];
  for (const code of FEATURED_IATA) {
    const a = byIata.get(code);
    if (a?.countryCode === cc) hits.push(a);
  }
  if (hits.length >= limit) return hits.slice(0, limit);
  for (const row of IATA_AIRPORTS) {
    if (row[3] !== cc) continue;
    const a = byIata.get(row[0])!;
    if (hits.some((h) => h.iata === a.iata)) continue;
    hits.push(a);
    if (hits.length >= limit) break;
  }
  return hits;
}
